name: Build GNU Toolchain

on:
  push:
    branches: [ v2004-toolchain-only-package ]
  pull_request:
    branches: [ v2004-toolchain-only-package ]

jobs:
  build_bare_linux_windows:
    name: baremetal for ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#         os: [ubuntu-latest]
        os: [ubuntu-16.04]
    env: 
      CC: gcc-8
      CXX: g++-8

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          sudo apt-get install cmake autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf patchutils bc zlib1g-dev libexpat-dev libtool pkg-config mingw-w64
    - name: Build Toolchain
      run: |
        make toolchain
    - name: Upload built linux toolchain artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14
        # A file, directory or wildcard pattern that describes what to upload
        path: riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz
    - name: Upload built windows toolchain artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-w64-mingw32
        # A file, directory or wildcard pattern that describes what to upload
        path: riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-w64-mingw32.tar.gz
